export type GroupedOptions = {
  group: string;
  options: Array<{ label: string; value: string }>;
};

export const PEST_PRODUCT_TYPES = [
  "pesticide",
  "insecticide",
  "fungicide",
  "herbicide",
  "nematicide",
  "growth_regulator",
  "adjuvant_surfactant",
] as const;

export const PRODUCT_FORM_GROUPS: GroupedOptions[] = [
  {
    group: "Liquid formulations",
    options: [
      { value: "EC", label: "EC – Emulsifiable Concentrate" },
      { value: "EW", label: "EW – Emulsion, Oil in Water" },
      { value: "SC", label: "SC – Suspension Concentrate" },
      { value: "SL", label: "SL – Soluble Liquid" },
      { value: "CS", label: "CS – Capsule Suspension" },
      { value: "ME", label: "ME – Microemulsion" },
      { value: "OD", label: "OD – Oil Dispersion" },
      { value: "SE", label: "SE – Suspo-Emulsion" },
      { value: "UL", label: "UL – Ultra Low Volume" },
      { value: "OF", label: "OF – Oil-based Flowable" },
      { value: "AL", label: "AL – Aqueous Liquid" },
      { value: "DC", label: "DC – Dispersible Concentrate" },
      { value: "LS", label: "LS – Liquid Seed Treatment" },
    ],
  },
  {
    group: "Solid formulations",
    options: [
      { value: "WP", label: "WP – Wettable Powder" },
      { value: "WG", label: "WG / WDG – Water Dispersible Granules" },
      { value: "WDG", label: "WDG" },
      { value: "WB", label: "WB" },
      { value: "GR", label: "GR – Granules" },
      { value: "SG", label: "SG – Soluble Granules" },
      { value: "DP", label: "DP – Dustable Powder" },
      { value: "SP", label: "SP – Soluble Powder" },
      { value: "BR", label: "BR – Briquettes" },
      { value: "TB", label: "TB – Tablets" },
    ],
  },
  {
    group: "Baits",
    options: [
      { value: "RB", label: "RB – Ready Bait" },
      { value: "GB", label: "GB – Granular Bait" },
      { value: "PB", label: "PB – Paste Bait" },
      { value: "BB", label: "BB – Block Bait" },
    ],
  },
  {
    group: "Seed treatment",
    options: [
      { value: "FS", label: "FS – Flowable Concentrate for Seed Treatment" },
      { value: "WS", label: "WS – Water Soluble Powder for Seed Treatment" },
      { value: "SS", label: "SS – Soluble Concentrate for Seed Treatment" },
      { value: "DS", label: "DS – Dry Seed Treatment" },
    ],
  },
  {
    group: "Aerosols & fumigants",
    options: [
      { value: "AE", label: "AE – Aerosol" },
      { value: "FU", label: "FU – Fumigant" },
      { value: "FG", label: "FG – Fine Granule" },
      { value: "GA", label: "GA – Gas" },
    ],
  },
  {
    group: "Biological & advanced formulations",
    options: [
      { value: "BC", label: "BC – Biological Concentrate" },
      { value: "BT", label: "BT – Bacillus thuringiensis formulations" },
      { value: "VP", label: "VP – Vapour Generating Product" },
      { value: "MC", label: "MC – Mosquito Coil" },
      { value: "PA", label: "PA – Paint Application" },
      { value: "CB", label: "CB – Concentrate Bait" },
    ],
  },
];

export const ACTIVE_INGREDIENT_GROUPS: GroupedOptions[] = [
  {
    group: "Insecticides / Acaricides / Nematicides",
    options: [
      "Abamectin",
      "Abamectin Bifenthrin",
      "Abamectin Bifenazate",
      "Acequinocyl",
      "Acetamiprid",
      "Alphacypermethrin",
      "Azadirachtin",
      "Bifenzate",
      "Bifenthrin",
      "Bifenazate",
      "Buprofezin",
      "Chlorantraniliprole",
      "Chlorpyrifos",
      "chlorantraniliprole Abamectin",
      "Cypermethrin",
      "Cyromazine",
      "Cyantraniliprole",
      "Diafenthiuron",
      "Diazinon",
      "Deltamethrin",
      "Diflubenzuron",
      "Dinotefuran",
      "Emamectin benzoate",
      "Fenitrothion",
      "Fenpyroximate",
      "Fipronil",
      "Flonicamid",
      "Fosthiazate",
      "Hexythiazox",
      "Imidacloprid",
      "Indoxacarb",
      "Lambda-cyhalothrin",
      "Lufenuron",
      "Methomyl",
      "Novaluron",
      "Oxamyl",
      "Pirimiphos-methyl",
      "Pyridaben",
      "Pyriproxyfen",
      "Spinosad",
      "Thiamethoxam",
      "Thiamethoxam Abamectin",
      "Thiodicarb",
      "Thiocyclam hydrogen oxalate",
      "Thocyclam Hydrogen Oxalate",
    ].map((v) => ({ value: v, label: v })),
  },
  {
    group: "Fungicides",
    options: [
      "Azoxystrobin",
      "Azoxystrobin Difenoconazole",
      "Boscalid",
      "Boscalid Pyraclostrobin",
      "Chinsol",
      "Copper hydroxide",
      "Copper oxychloride",
      "Carbendazim",
      "Chlorothalonil",
      "Cyproconazole",
      "Cymoxanil",
      "Difenoconazole",
      "Dimethomorph",
      "Fenhexamid",
      "Flutriafol",
      "Fosetyl-aluminium",
      "Flutianil",
      "Hymexazol",
      "Mancozeb",
      "Metalaxyl",
      "Metalaxyl-M",
      "Penthiopirad",
      "Prochloraz",
      "Propiconazole",
      "Propamocarb hydrochloride",
      "Pyraclostrobin",
      "Sulfur",
      "Tebuconazole",
      "Thiophanate-methyl",
      "Tolcofos - Methyl",
      "Tolclofos-methyl",
    ].map((v) => ({ value: v, label: v })),
  },
  {
    group: "Herbicides",
    options: [
      "2,4-D amine",
      "Atrazine",
      "Bromoxynil octanoate",
      "Bromoxynil Octanoate Diflufenican",
      "Clethodim",
      "Diflufenican",
      "Diuron",
      "Fluazifop-P-butyl",
      "Fomesafen",
      "Glufosinate-ammonium",
      "Glyphosate IPA",
      "Glyphosate (IPA salt)",
      "Halosulfuron-methyl",
      "Metribuzin",
      "Metsulfuron-methyl",
      "Nicosulfuron",
      "Pendimethalin",
      "Paraquat dichloride",
      "Pyroxasulfone",
      "S-metolachlor",
      "Tribenuron Methyl",
      "Tribenuron-methyl",
    ].map((v) => ({ value: v, label: v })),
  },
  {
    group: "Oils & Adjuvants",
    options: ["Mineral oil", "Paraffinic mineral oil"].map((v) => ({
      value: v,
      label: v,
    })),
  },
];

export const DOSE_UNIT_OPTIONS = [
  "mg",
  "g",
  "kg",
  "ml",
  "L",
  "powder",
  "other",
] as const;

export const ACTIVE_INGREDIENT_TARGET_MAP: Record<string, string[]> = {
  // Insecticides / Acaricides / Nematicides
  "Abamectin": [
    "Mites",
    "spider mites",
    "leaf miners",
    "whiteflies",
    "thrips",
    "some caterpillars",
    "foliar nematodes",
  ],
  "Acequinocyl": [
    "Spider mites",
    "two-spotted mites",
    "phytophagous mites",
  ],
  "Acetamiprid": [
    "Aphids",
    "whiteflies",
    "mealybugs",
    "leafhoppers",
    "scale insects",
  ],
  "Alphacypermethrin": [
    "Chewing insects",
    "caterpillars",
    "cutworms",
    "stem borers",
    "grasshoppers",
    "flies",
    "mosquitoes",
  ],
  "Azadirachtin": [
    "Aphids",
    "whiteflies",
    "thrips",
    "caterpillars",
    "scale insects",
    "leaf beetles",
  ],
  "Bifenthrin": [
    "Ants",
    "caterpillars",
    "soil insects",
    "mites",
    "flies",
    "mosquitoes",
  ],
  "Bifenazate": ["Spider mites", "red mites"],
  "Buprofezin": [
    "Whiteflies",
    "planthoppers",
    "scale insects",
    "immature sucking pests",
  ],
  "Chlorantraniliprole": [
    "Lepidopteran larvae",
    "leaf-feeding caterpillars",
    "fruit borers",
    "stem borers",
    "fall armyworm",
  ],
  "Chlorpyrifos": [
    "Soil insects",
    "cutworms",
    "stem borers",
    "termites",
    "leaf-feeding insects",
  ],
  "Cypermethrin": [
    "Chewing insects",
    "caterpillars",
    "stem borers",
    "grasshoppers",
    "flies",
  ],
  "Cyromazine": ["Fly larvae", "leaf miners"],
  "Cyantraniliprole": [
    "Thrips",
    "whiteflies",
    "leaf miners",
    "caterpillars",
    "aphids",
  ],
  "Diafenthiuron": ["Whiteflies", "mites", "thrips"],
  "Diazinon": ["Soil insects", "aphids", "leafhoppers", "flies", "ants"],
  "Deltamethrin": [
    "Chewing and sucking insects",
    "caterpillars",
    "flies",
    "mosquitoes",
    "locusts",
  ],
  "Diflubenzuron": [
    "Caterpillar larvae",
    "leaf-feeding larvae",
    "immature insect stages",
  ],
  "Dinotefuran": [
    "Aphids",
    "whiteflies",
    "leafhoppers",
    "scale insects",
    "mealybugs",
  ],
  "Emamectin benzoate": [
    "Leaf-feeding caterpillars",
    "armyworms",
    "tomato fruitworm",
    "leaf miners",
  ],
  "Fenitrothion": [
    "Chewing insects",
    "stored-product insects",
    "locusts",
    "flies",
  ],
  "Fenpyroximate": ["Spider mites", "phytophagous mites"],
  "Fipronil": ["Ants", "termites", "cockroaches", "soil insects", "root feeders"],
  "Flonicamid": ["Aphids", "whiteflies", "leafhoppers"],
  "Fosthiazate": ["Root-knot nematodes", "soil nematodes"],
  "Hexythiazox": ["Spider mite eggs", "immature mite stages"],
  "Imidacloprid": [
    "Aphids",
    "whiteflies",
    "leafhoppers",
    "scale insects",
    "mealybugs",
  ],
  "Indoxacarb": ["Caterpillars", "armyworms", "chewing larvae"],
  "Lambda-cyhalothrin": [
    "Chewing and sucking insects",
    "caterpillars",
    "grasshoppers",
    "flies",
  ],
  "Lufenuron": [
    "Caterpillars",
    "leaf-feeding larvae",
    "beetle larvae (insect growth regulator)",
  ],
  "Methomyl": [
    "Caterpillars",
    "thrips",
    "leaf miners",
    "beetles",
    "chewing insects",
  ],
  "Novaluron": [
    "Caterpillars",
    "leaf-feeding larvae",
    "whiteflies",
    "beetle larvae",
  ],
  "Oxamyl": ["Nematodes", "soil insects", "aphids", "whiteflies"],
  "Pirimiphos-methyl": ["Grain weevils", "beetles", "moths (stored-product pests)"],
  "Pyridaben": ["Spider mites", "whiteflies"],
  "Pyriproxyfen": [
    "Whiteflies",
    "immature insect stages",
    "scale insects (growth regulator)",
  ],
  "Spinosad": ["Caterpillars", "thrips", "leaf miners", "fruit flies"],
  "Thiamethoxam": [
    "Aphids",
    "whiteflies",
    "leafhoppers",
    "scale insects",
  ],
  "Thiodicarb": ["Caterpillars", "cutworms"],
  "Thiocyclam hydrogen oxalate": ["Leaf miners", "caterpillars", "chewing larvae"],

  // Fungicides
  "Azoxystrobin": ["Powdery mildew", "downy mildew", "leaf spots", "rusts", "early blight"],
  "Boscalid": ["Gray mold (Botrytis)", "root rots", "fruit rots"],
  "Carbendazim": [
    "Leaf spots",
    "powdery mildew",
    "anthracnose",
    "fruit rots",
  ],
  "Chlorothalonil": [
    "Leaf spots",
    "early blight",
    "downy mildew suppression",
    "anthracnose",
  ],
  "Chinsol": ["Soil-borne diseases", "root rot"],
  "Copper hydroxide": ["Bacterial spot", "bacterial blight", "leaf spots", "fire blight"],
  "Copper oxychloride": ["Bacterial spot", "bacterial blight", "leaf spots", "fire blight"],
  "Cyproconazole": ["Rusts", "leaf spots", "powdery mildew"],
  "Cymoxanil": ["Downy mildew", "late blight", "oomycete diseases"],
  "Difenoconazole": ["Powdery mildew", "rusts", "leaf spots", "blights"],
  "Dimethomorph": ["Downy mildew", "Phytophthora", "oomycete diseases"],
  "Fenhexamid": ["Gray mold (Botrytis)"],
  "Flutriafol": ["Rusts", "powdery mildew", "leaf spots"],
  "Fosetyl-aluminium": ["Phytophthora", "Pythium", "root and crown rots"],
  "Flutianil": ["Powdery mildew"],
  "Hymexazol": ["Damping-off", "root rot", "seedling diseases"],
  "Mancozeb": ["Downy mildew", "leaf spots", "rusts", "anthracnose", "blights"],
  "Metalaxyl": ["Pythium", "Phytophthora", "downy mildews"],
  "Metalaxyl-M": ["Pythium", "Phytophthora", "downy mildews"],
  "Penthiopirad": ["Botrytis", "Alternaria", "powdery mildew", "soil-borne diseases"],
  "Prochloraz": ["Root rots", "stem rots", "leaf spots"],
  "Propiconazole": ["Rusts", "powdery mildew", "leaf spots"],
  "Propamocarb hydrochloride": ["Downy mildew", "soil-borne diseases"],
  "Pyraclostrobin": ["Leaf spots", "rusts", "blights"],
  "Sulfur": ["Powdery mildew", "mite suppression"],
  "Tebuconazole": ["Rusts", "powdery mildew", "leaf spots"],
  "Thiophanate-methyl": ["Anthracnose", "powdery mildew", "leaf spots", "fruit rots"],
  "Tolclofos-methyl": ["Rhizoctonia", "soil-borne rots"],

  // Herbicides
  "2,4-D amine": ["Broadleaf weeds (post-emergence)"],
  "Atrazine": ["Annual broadleaf weeds", "annual grasses (pre/post-emergence)"],
  "Bromoxynil octanoate": ["Annual broadleaf weeds"],
  "Clethodim": ["Annual and perennial grass weeds"],
  "Diflufenican": ["Broadleaf weeds", "some grasses"],
  "Diuron": ["Annual grasses", "broadleaf weeds", "residual pre-emergence weeds"],
  "Fluazifop-P-butyl": ["Annual and perennial grass weeds (post-emergence)"],
  "Fomesafen": ["Broadleaf weeds", "nightshade", "amaranth"],
  "Glufosinate-ammonium": ["Annual and perennial weeds", "broadleaf weeds", "grasses"],
  "Glyphosate IPA": ["Annual and perennial weeds", "woody plants"],
  "Glyphosate (IPA salt)": ["Annual and perennial weeds", "woody plants"],
  "Halosulfuron-methyl": ["Nutsedge", "selected broadleaf weeds"],
  "Metribuzin": ["Grass and broadleaf weeds"],
  "Metsulfuron-methyl": ["Broadleaf weeds", "woody brush", "sedges (selective use)"],
  "Nicosulfuron": ["Annual grasses", "johnsongrass", "select broadleaf weeds"],
  "Pendimethalin": ["Pre-emergence grass and broadleaf weeds"],
  "Paraquat dichloride": ["Fast burndown of emerged annual weeds"],
  "Pyroxasulfone": ["Pre-emergence grass and broadleaf weeds"],
  "S-metolachlor": ["Grass weeds", "some broadleaf weeds"],
  "Tribenuron-methyl": ["Broadleaf weeds"],

  // Oils & Adjuvants
  "Mineral oil": [
    "Sucking insects",
    "insect eggs",
    "spray coverage enhancement",
    "efficacy improvement",
  ],
  "Paraffinic mineral oil": [
    "Sucking insects",
    "insect eggs",
    "spray coverage enhancement",
    "efficacy improvement",
  ],
};
