export const OPENAPI_BLOCKER_IDS = {
  AUTH_REQUEST_DTOS: 'QH-OAPI-001',
  SUBSCRIPTION_RESPONSE_SCHEMAS: 'QH-OAPI-002',
  FIELDS_LOTS_REQUEST_DTOS: 'QH-OAPI-003',
  FIELDS_LOTS_RESPONSE_SCHEMAS: 'QH-OAPI-004',
  DASHBOARD_SNAPSHOT_RESPONSE_SCHEMA: 'QH-OAPI-005',
  TASKS_REQUEST_DTOS: 'QH-OAPI-006',
  TASKS_RESPONSE_SCHEMAS: 'QH-OAPI-007',
  PRODUCTS_HARD_DELETE_REQUEST_DTO: 'QH-OAPI-012',
  PHASE10_STORE_DASHBOARD_CONTRACTS: 'QH-OAPI-019',
} as const;
