import { MD3LightTheme, type MD3Theme } from 'react-native-paper';
import { palette } from './tokens';

export const appTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 16,
  colors: {
    ...MD3LightTheme.colors,
    primary: palette.primary,
    onPrimary: palette.onPrimary,
    primaryContainer: '#D8EFDD',
    onPrimaryContainer: palette.primaryDark,
    secondary: palette.secondary,
    onSecondary: palette.onSecondary,
    secondaryContainer: '#F3EEE7',
    onSecondaryContainer: palette.foreground,
    tertiary: palette.accent,
    onTertiary: palette.onAccent,
    tertiaryContainer: '#FFF3CC',
    onTertiaryContainer: '#4A3A0B',
    background: palette.background,
    onBackground: palette.foreground,
    surface: palette.surface,
    onSurface: palette.foreground,
    surfaceVariant: palette.surfaceVariant,
    onSurfaceVariant: palette.mutedForeground,
    surfaceDisabled: '#EDF2F0',
    onSurfaceDisabled: '#8EA196',
    outline: palette.border,
    outlineVariant: palette.border,
    error: palette.destructive,
    onError: palette.onDestructive,
    errorContainer: '#FDE4E4',
    onErrorContainer: '#641F1F',
    inverseSurface: palette.foreground,
    inverseOnSurface: palette.background,
    inversePrimary: palette.primaryLight,
    backdrop: 'rgba(23, 38, 31, 0.30)',
    elevation: {
      level0: 'transparent',
      level1: '#F7FAF8',
      level2: '#F3F8F5',
      level3: '#EEF5F1',
      level4: '#EBF4EF',
      level5: '#E8F1EC',
    },
  },
};
